
#-----------------------------------------------------------------------

APP       := IMGroupChatApp
TARGET    := IMGroupChatServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       +=libslog.so

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
